version: "3.4"

services:

  timescale:
    image: timescale/timescaledb:latest-pg10
    container_name: timescale
    hostname: timescale
    ports:
      - 5432:5432
    env_file: ./conf/timescale-env.list
    volumes:
      - timescale_data:/var/lib/postgresql

  grafana:
    image: grafana/grafana:6.3.4
    container_name: grafana
    hostname: grafana
    ports:
      - 3000
    environment:
      - NO_PROXY
      - GF_SERVER_DOMAIN=ip-10-227-54-255.ec2.internal
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s/grafana/
    volumes:
      - grafana_data:/var/lib/grafana
      - grafana_data:/var/log/grafana

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    hostname: pgadmin
    ports: 
      - 80
    env_file: ./conf/pgadmin-env.list 
    volumes: 
      - pgadmin_data:/var/lib/pgadmin
  
  portainer:
    image: portainer/portainer
    container_name: portainer
    hostname: portainer
    restart: always
    ports:
      - 9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  nginx: 
    image: nginx:latest
    container_name: nginx
    hostname: nginx
    restart: always
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

volumes:
  pgadmin_data:
    name: pgadmin_data
  grafana_data:
    name: grafana_data
  portainer_data:
    name: portainer_data
  timescale_data:
    name: timescale_data