version: "3.4"

services:
  postgres:
    image: postgres/postgres:10.10-alpine
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    env_file: ./conf/pg-env.list
    volumes:
      - postgres_data:/var/lib/postgresql

  grafana:
    image: grafana/grafana:6.3.4
    container_name: grafana
    hostname: grafana
    ports:
      - 9001:9001
    environment:
      - GF_SERVER_HTTP_PORT=9001
      - NO_PROXY
    volumes:
      - grafana_data:/var/lib/grafana
      - grafana_data:/var/log/grafana

  pg_admin:
    image: dpage/pgadmin4:latest
    container_name: pg_admin
    hostname: pg_admin
    ports: 
      - 9002:80
    env_file: ./conf/pgadmin-env.list 
    volumes: 
      - pgadmin_data:/var/lib/pgadmin
  
  portainer:
    image: portainer/portainer
    container_name: portainer
    hostname: portainer
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  postgres:
    name: postgres_data
  pg_admin:
    name: pg_admin_data
  grafana:
    name: grafana_data
  portainer:
    name: portainer_data